version: "2"

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gosec
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - prealloc
    - gocritic
