version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - ENVIRONMENT=development
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080
    restart: unless-stopped
    networks:
      - subspace-network

networks:
  subspace-network:
    driver: bridge
